# Generated by Django 5.1.1 on 2024-09-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='state',
            field=models.CharField(choices=[('Azad Jammu and Kashmir', 'Azad Jammu and Kashmir'), ('Balochistan', 'Balochistan'), ('Gilgit-Baltistan', 'Gilgit-Baltistan'), ('Islamabad Capital Territory', 'Islamabad Capital Territory'), ('Khyber Pakhtunkhwa', 'Khyber Pakhtunkhwa'), ('Punjab', 'Punjab'), ('Sindh', 'Sindh'), ('FATA', 'FATA')], max_length=50),
        ),
    ]
